replicaCount: 2

image:
  repository: docker.io/eknathdj/cloudwave-wordpress
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: wordpress.cloudwave.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 125m
    memory: 256Mi

mysql:
  enabled: true
  image:
    repository: mysql
    tag: "8.0"
  auth:
    rootPassword: "rootpassword"
    database: "wordpress"
    username: "wordpress"
    password: "wordpresspass"
  primary:
    persistence:
      enabled: true
      size: 10Gi