apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudwave-api-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/eknathdj/devops-gitops-argocd-gha-helm'
    targetRevision: HEAD
    path: charts/myapp
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cloudwave
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
