replicaCount: 2

image:
  repository: docker.io/eknathdj/cloudwave-api
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

readinessProbe:
  path: /
  port: 8080

livenessProbe:
  path: /
  port: 8080

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"
