apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-sample-app
  namespace: devops-sample
  labels:
    app: devops-sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-sample-app
  template:
    metadata:
      labels:
        app: devops-sample-app
    spec:
      containers:
        - name: devops-sample-app
          image: ghcr.io/eknathdj/devops-sample-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
