apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudwave-api
  namespace: cloudwave
  labels:
    app: cloudwave-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudwave-api
  template:
    metadata:
      labels:
        app: cloudwave-api
    spec:
      containers:
        - name: cloudwave-api
          image: docker.io/eknathdj/cloudwave-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
