apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: cloudwave
type: Opaque
data:
  # Base64 encoded passwords - change these in production!
  # root-password: "your-root-password" (base64 encoded)
  # user-password: "your-user-password" (base64 encoded)
  root-password: cm9vdHBhc3N3b3Jk  # rootpassword
  user-password: d29yZHByZXNzcGFzcw==  # wordpresspass