apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: docker.io/eknathdj/cloudwave-api
    newTag: "cb0071a88800c1528bd25e13a4c30f4a5e61dded"
  - name: docker.io/eknathdj/cloudwave-wordpress
    newTag: "cb0071a88800c1528bd25e13a4c30f4a5e61dded"
