name: CI-CD Simple (Build -> Scan -> Push -> GitOps Update)

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [deploy-simple, quick-deploy, trigger-simple-ci]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Display trigger info
        run: |
          echo "Workflow triggered by: ${{ github.event_name }}"
          if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
            echo "Dispatch event type: ${{ github.event.action }}"
            echo "Client payload: ${{ toJson(github.event.client_payload) }}"
          fi

      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - run: mvn -B clean compile test package

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push image
        id: build-image
        run: |
          IMAGE=${{ secrets.REGISTRY }}/${{ github.repository_owner }}/cloudwave-api
          TAG=${{ github.sha }}
          docker build -t $IMAGE:$TAG .
          docker push $IMAGE:$TAG
          echo "IMAGE=$IMAGE:$TAG" >> $GITHUB_OUTPUT

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.build-image.outputs.IMAGE }}
          exit-code: "0" # set to 0 to continue pipeline even with vulnerabilities (for testing)
        continue-on-error: true # Continue pipeline even if Trivy step fails

      - name: Update kustomization file (simple sed)
        run: |
          FILE=k8s/overlays/dev/kustomization.yaml
          sed -i "s/newTag: .*/newTag: \"${{ github.sha }}\"/" $FILE || true
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add $FILE
          git commit -m "chore: bump image tag to ${{ github.sha }}" || echo "no changes"
          git push origin HEAD:${{ github.ref_name }}
